#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZoomRemote.Resource", IsApplication=true)]

namespace ZoomRemote
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int AmberBar = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buttonbgdown = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int buttonbgnormal = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ButtonMark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ButtonNext = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ButtonPlay = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ButtonPrev = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int ButtonRecord = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int ButtonRecordPause = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int ButtonRecordRed = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int ButtonVolDown = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int ButtonVolUp = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int GreenBar = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int GreyBar = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int Icon = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int LevelBackgroundDefault = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int LevelForeground = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int RedBar = 2130771985;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int buttonMarkIcon = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int buttonNextIcon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int buttonPlayIcon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int buttonPrevIcon = 2130837507;
			
			// aapt resource value: 0x7F020005
			public const int buttonRecordIcon = 2130837509;
			
			// aapt resource value: 0x7F020004
			public const int buttonRecPauseIcon = 2130837508;
			
			// aapt resource value: 0x7F020006
			public const int buttonVolDownIcon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int buttonVolUpIcon = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int button_endscan = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int button_launch_scan = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int button_scan = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int deviceName = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int gridViewPlay = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int gridViewRecord = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int indeterminateBar = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int level1 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int level2 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int selectionPrompt = 2130837521;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int DeviceControl = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int DeviceListLayout = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int button_endscan = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int button_scan = 2130968579;
			
			// aapt resource value: 0x7F040006
			public const int connected = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int connecting = 2130968583;
			
			// aapt resource value: 0x7F040004
			public const int connect_prev = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int connect_prev_summ = 2130968581;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040008
			public const int init_string_1 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int init_string_2 = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int init_string_3 = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int init_string_default_1 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int init_string_default_2 = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int init_string_default_3 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int init_string_summ_1 = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int init_string_summ_2 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int init_string_summ_3 = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int last_device = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int last_device_summ = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int menu_advanced_text = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int menu_scan_text = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int none_found = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int none_paired = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int scanning = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int select_device = 2130968600;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F050000
			public const int preferences = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
