#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZoomRemote.Resource", IsApplication=true)]

namespace ZoomRemote
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonbgdown = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonbgnormal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonMicDown = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonMicUp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ButtonNext = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ButtonPlay = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ButtonPrev = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ButtonRecord = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ButtonSeparatorHorizontal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ButtonStop = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ButtonVolDown = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ButtonVolUp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ButtonWidth = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int LevelBackgroundDefault = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int LevelBackgroundDefaultSml = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int LevelForeground = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int MyButton = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int buttonMicDownIcon = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int buttonMicUpIcon = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int buttonNextIcon = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int buttonPlayIcon = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int buttonPrevIcon = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int buttonRecordIcon = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int buttonStopIcon = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int buttonVolDownIcon = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int buttonVolUpIcon = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int buttonWidthIcon = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int button_scan = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int debugStateText = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int gridViewPlay = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int gridViewRecord = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int levelLine1Icon = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int levelLine2Icon = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int levelMicIcon = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int new_devices = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int paired_devices = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int title_new_devices = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int title_paired_devices = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DeviceControl = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeviceListLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeviceNameLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int button_scan = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int none_found = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int none_paired = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int scanning = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int select_device = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int title_other_devices = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int title_paired_devices = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
